Python 2.7:
  script:
  - export PY_EXE=python2.7
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3:
  script:
  - export PY_EXE=python3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 small integer opt:
  script:
  - export PY_EXE=python3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ./configure.py --use-imath-sio
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 + Barvinok:
  script:
  - git clean -fdx
  - python3 -m venv .env
  - source .env/bin/activate
  - python -m ensurepip
  - pip install cffi
  - "./build-with-barvinok.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml


PyPy:
  script:
  - export PY_EXE=pypy
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - pypy
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3
  only:
  - master
