Python 3:
  script: |
    EXTRA_INSTALL="numpy"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
    . ./build-and-test-py-project.sh
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Examples:
  script: |
    EXTRA_INSTALL="matplotlib numpy"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
    . ./ci-support.sh
    build_py_project_in_venv
    run_examples
  tags:
  - python3
  except:
  - tags

Python 3 small integer opt:
  script:
  - export PY_EXE=python3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ./configure.py --use-imath-sio
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Python 3 + Barvinok:
  script:
  - git clean -fdx
  - python3 -m venv .env
  - source .env/bin/activate
  - python -m ensurepip
  - pip install cffi pcpp
  - "./build-with-barvinok.sh"
  tags:
  - python3
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

PyPy3:
  script:
  - export PY_EXE=pypy3
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  allow_failure: true
  tags:
  - pypy
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Documentation:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" test gen_wrap.py examples
  tags:
  - python3
