blank_issues_enabled: true
contact_links:
  - name: ❓ Question
    url: https://github.com/inducer/islpy/discussions/categories/q-a
    about: Ask and answer questions about islpy on Discussions
  - name: 🔧 Troubleshooting
    url: https://github.com/inducer/islpy/discussions/categories/troubleshooting
    about: For troubleshooting help, see the Discussions
